// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const url =
  process.env["DATABASE_URL"] ??
  (process.env["NODE_ENV"] === "production"
    ? undefined
    : "file:./prisma/dev.db");

if (!url) {
  throw new Error(
    "Missing DATABASE_URL environment variable. Set it in your Netlify project settings."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url,
  },
});
