export const ABOUT_LOCATORS = {
  heroSection: '[data-testid="about-hero-section"]',
  heroTextContainer: '[data-testid="about-hero-text-container"]',
  heroLabelReal: '[data-testid="about-hero-label"]:not([aria-hidden="true"])',
  heroHeadingReal: '[data-testid="about-hero-heading"]:not([aria-hidden="true"])',
  heroParagraphReal: '[data-testid="about-hero-paragraph"]:not([aria-hidden="true"])',
  heroImageWrapper: '[data-testid="about-hero-image-wrapper"]',
  heroImage: '[data-testid="about-hero-image"]',
  missionVisionSection: '[data-testid="mission-vision-section"]',
  missionVisionSectionHeading: '[data-testid="mission-vision-section-heading"]',
  missionVisionSectionParagraph: '[data-testid="mission-vision-section-paragraph"]',
  missionCard: '[data-testid="mission-card"]',
  missionCardHeading: '[data-testid="mission-card-heading"]',
  missionCardBody: '[data-testid="mission-card-body"]',
  missionCardImage: '[data-testid="mission-card-image"]',
  visionCard: '[data-testid="vision-card"]',
  visionCardHeading: '[data-testid="vision-card-heading"]',
  visionCardBody: '[data-testid="vision-card-body"]',
  visionCardImage: '[data-testid="vision-card-image"]',
  pressReleasesSection: '[data-testid="press-releases-section"]',
  pressReleasesSectionHeading: '[data-testid="press-releases-section-heading"]',
  pressReleasesSectionParagraph: '[data-testid="press-releases-section-paragraph"]',
  pressReleasesGrid: '[data-testid="press-releases-grid"]',
  pressReleaseCard1: '[data-testid="press-release-card-1"]',
  pressReleaseCardTitle1: '[data-testid="press-release-card-title-1"]',
  pressReleaseCardDate1: '[data-testid="press-release-card-date-1"]',
  pressReleaseCardExcerpt1: '[data-testid="press-release-card-excerpt-1"]',
} as const;
