export const HOMEPAGE_LOCATORS = {
  navbar: '[data-testid="navbar"]',
  navbarLogo: '[data-testid="navbar-logo"]',
  navLogin: '[data-testid="nav-login"]',
  navSignUp: '[data-testid="nav-sign-up"]',
  navUser: '[data-testid="nav-user"]',
  navLogout: '[data-testid="nav-logout"]',
  mobileMenuButton: '[data-testid="nav-mobile-toggle"]',
  mobileMenu: '[data-testid="mobile-menu"]',
  mobileLogin: '[data-testid="mobile-login"]',
  mobileSignUp: '[data-testid="mobile-sign-up"]',
  ctaSection: '[data-testid="cta-section"]',
  ctaHeading: '[data-testid="cta-heading"]',
  ctaBody: '[data-testid="cta-body"]',
  ctaButton: '[data-testid="cta-button"]',
  // Real content excludes the SWR loading skeleton, which is aria-hidden.
  ctaHeadingReal: '[data-testid="cta-heading"]:not([aria-hidden="true"])',
  ctaBodyReal: '[data-testid="cta-body"]:not([aria-hidden="true"])',
  ctaButtonReal: '[data-testid="cta-button"]:not([aria-hidden="true"])',
  // BC-13 — Testimonials Section
  testimonialsSection: '[data-testid="testimonials-section"]',
  testimonialsHeading: '[data-testid="testimonials-heading"]',
  testimonialsSubheading: '[data-testid="testimonials-subheading"]',
  testimonialsTabIndividuals: '[data-testid="testimonials-tab-individuals"]',
  testimonialsTabBusinesses: '[data-testid="testimonials-tab-businesses"]',
  testimonialsCard: '[data-testid^="testimonials-card-"]',
  testimonialsPrev: '[data-testid="testimonials-prev"]',
  testimonialsNext: '[data-testid="testimonials-next"]',
  // BC-21 — Hero Section
  heroSection: '[data-testid="hero-section"]',
  heroBadge: '[data-testid="hero-badge"]',
  heroBadgeIcon: '[data-testid="hero-badge-icon"]',
  heroHeading: '[data-testid="hero-heading"]',
  heroHeadingReal: '[data-testid="hero-heading"]:not([aria-hidden="true"])',
  heroLineWelcome: '[data-testid="hero-line-welcome"]',
  heroParagraph: '[data-testid="hero-paragraph"]',
  heroParagraphReal: '[data-testid="hero-paragraph"]:not([aria-hidden="true"])',
  heroOpenAccount: '[data-testid="hero-open-account"]',
  heroOpenAccountReal: '[data-testid="hero-open-account"]:not([aria-hidden="true"])',
  heroMockup: '[data-testid="hero-mockup"]',
  heroMonthlyIncome: '[data-testid="hero-monthly-income"]',
  heroMonthlyIncomeReal: '[data-testid="hero-monthly-income"]:not([aria-hidden="true"])',
  heroTransactionsCard: '[data-testid="hero-transactions-card"]',
  heroTransactionsCardReal: '[data-testid="hero-transactions-card"]:not([aria-hidden="true"])',
  heroTransactionsHeading: '[data-testid="hero-transactions-heading"]',
  heroExchangeCard: '[data-testid="hero-exchange-card"]',
  heroExchangeHeading: '[data-testid="hero-exchange-heading"]',
  heroSupportedCurrency: '[data-testid="hero-supported-currency"]',
  heroSupportedCurrencyReal: '[data-testid="hero-supported-currency"]:not([aria-hidden="true"])',
  heroBackgroundArrows: '[data-testid="hero-background-arrows"]',
  heroAbstractIllustration: '[data-testid="hero-abstract-illustration"]',
  // BC-24 — Products Section
  productsSection: '[data-testid="products-section"]',
  productsHeading: '[data-testid="products-heading"]',
  productsSubheading: '[data-testid="products-subheading"]',
  productsTabs: '[data-testid="products-tabs"]',
  productsTabIndividuals: '[data-testid="products-tab-individuals"]',
  productsTabBusinesses: '[data-testid="products-tab-businesses"]',
  productsGrid: '[data-testid="products-grid"]',
  productsCard: 'article[data-testid^="product-card-"]',
  productsCardFirst: '[data-testid="product-card-1"]',
  productsTitleFirst: '[data-testid="product-title-1"]',
  // BC-27 — Use Cases Section
  useCasesSection: '[data-testid="use-cases-section"]',
  useCasesHeading: '[data-testid="use-cases-heading"]',
  useCasesSubheading: '[data-testid="use-cases-subheading"]',
  useCasesRowIndividuals: '[data-testid="use-cases-row-individuals"]',
  useCasesRowBusinesses: '[data-testid="use-cases-row-businesses"]',
  useCaseCard: 'article[data-testid^="use-case-card-"]',
  useCaseCardFirst: '[data-testid="use-case-card-1"]',
  useCaseTitleFirst: '[data-testid="use-case-title-1"]',
  // BC-30 — Features Section
  featuresSection: '[data-testid="features-section"]',
  featuresHeading: '[data-testid="features-heading"]',
  featuresCardsGrid: '[data-testid="features-cards-grid"]',
  featureCard: 'article[data-testid^="feature-card-"]',
  featureCardTitle: '[data-testid^="feature-card-title-"]',
} as const;
