#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

protected_branch='main'
current_branch=$(git symbolic-ref --short HEAD)

if [ "$current_branch" = "$protected_branch" ]; then
  echo "❌ Direct push to '$protected_branch' is not allowed. Please create a feature branch and open a pull request."
  exit 1
fi

npx lint-staged
